version: "3"

services:
  apps:
    image: openjdk:17.0.1-jdk
    working_dir: /opt/apps
    command: ./mvnw spring-boot:run 
    volumes:
      - .:/opt/apps
      - m2:/root/.m2
    ports:
      - "8080:8080"

  postgres:
    build: ./postgres/.
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  pgdata:
  m2:
    external: true