-- データベースの切り替え
\c mini_cactpot

-- テーブルの作成
CREATE TABLE m_payout (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    sum smallint,
    mgp smallint,
    PRIMARY KEY (id)
);

-- 初期データの投入
INSERT INTO m_payout (sum, mgp) VALUES ( 6, 10000);
INSERT INTO m_payout (sum, mgp) VALUES ( 7, 36);
INSERT INTO m_payout (sum, mgp) VALUES ( 8, 720);
INSERT INTO m_payout (sum, mgp) VALUES ( 9, 360);
INSERT INTO m_payout (sum, mgp) VALUES (10, 80);
INSERT INTO m_payout (sum, mgp) VALUES (11, 252);
INSERT INTO m_payout (sum, mgp) VALUES (12, 108);
INSERT INTO m_payout (sum, mgp) VALUES (13, 72);
INSERT INTO m_payout (sum, mgp) VALUES (14, 54);
INSERT INTO m_payout (sum, mgp) VALUES (15, 180);
INSERT INTO m_payout (sum, mgp) VALUES (16, 72);
INSERT INTO m_payout (sum, mgp) VALUES (17, 180);
INSERT INTO m_payout (sum, mgp) VALUES (18, 119);
INSERT INTO m_payout (sum, mgp) VALUES (19, 36);
INSERT INTO m_payout (sum, mgp) VALUES (20, 306);
INSERT INTO m_payout (sum, mgp) VALUES (21, 1080);
INSERT INTO m_payout (sum, mgp) VALUES (22, 144);
INSERT INTO m_payout (sum, mgp) VALUES (23, 1800);
INSERT INTO m_payout (sum, mgp) VALUES (24, 3600);
